# Generated by Django 3.1.7 on 2021-03-19 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Novel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=50)),
                ('title', models.TextField(max_length=100)),
                ('subtitle', models.TextField(max_length=100)),
                ('createDate', models.DateTimeField()),
            ],
        ),
    ]
