# Generated by Django 3.1.7 on 2021-03-19 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='novel',
            name='content',
            field=models.TextField(default='nono', max_length=2000),
            preserve_default=False,
        ),
    ]
