# Generated by Django 3.1.7 on 2021-03-16 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_auto_20210316_0609'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='modifiedDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
