# Generated by Django 3.1.7 on 2021-03-17 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_question_modifieddate'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='modifyDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
